name: Get archived SonarQube projects

on: workflow_dispatch

jobs:
  get-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Get archived GitHub repositories
        shell: pwsh
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_GH_PAT }}
          GITHUB_ORGANIZATION: "RoyalAholdDelhaize"
          SONARQUBE_DOMAIN_NAME: "sonar.ah.nl"
          SONARQUBE_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          . .\Scripts\Sonar-ArchivedGHRepos.ps1
          $archivedGitHubRepos = Get-ArchivedGHRepo -ghOrganization $env:GITHUB_ORGANIZATION -ghToken $env:GITHUB_TOKEN
          $archivedGitHubRepos | Out-File -FilePath .\archivedRepos.txt

      - name: Print the result
        shell: pwsh
        run: |
          Write-Output "List of repos:" 
          Get-Content .\archivedRepos.txt

      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: archivedRepos.txt

