name: Get archived SonarQube projects

on: workflow_dispatch

jobs:
  get-gh-repos:
    runs-on: ubuntu-latest
    outputs: 
      ghrepolist: ${{ steps.contents.outputs.ghrepolist }}
    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Get archived GitHub repositories
        shell: pwsh
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_GH_PAT }}
          GITHUB_ORGANIZATION: "RoyalAholdDelhaize"
        run: |
          . .\Scripts\Sonar-ArchivedGHRepos.ps1
          $archivedGitHubRepos = Get-ArchivedGHRepo -ghOrganization $env:GITHUB_ORGANIZATION -ghToken $env:GITHUB_TOKEN
          $archivedGitHubRepos | Out-File -FilePath .\archivedGHRepos.txt

      - name: Content export 
        id: contents
        run:
          contents=$( cat archivedGHRepos.txt )
          echo "::set-output name=ghrepolist::$contents"

  get-content:
    runs-on: ubuntu-latest
    needs: get-gh-repos
    steps:
      - name: Print the result
        shell: pwsh
        run: |
          Write-Output "List of repos:" 
          ${{ needs.get-gh-repos.outputs.ghrepolist }}
