name: Get archived SonarQube projects

on: workflow_dispatch

jobs:
  get-gh-repos:
    runs-on: ubuntu-latest
    outputs: 
      ghrepolist: ${{ steps.contents.outputs.ghrepolist }}
    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Get archived GitHub repositories
        id: contents
        shell: pwsh
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_GH_PAT }}
          GITHUB_ORGANIZATION: "RoyalAholdDelhaize"
          SONARQUBE_DOMAIN_NAME: "sonar.ah.nl"
          SONARQUBE_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          . .\Scripts\Sonar-ArchivedGHRepos.ps1
          $archivedGitHubRepos = Get-ArchivedGHRepo -ghOrganization $env:GITHUB_ORGANIZATION -ghToken $env:GITHUB_TOKEN
          "ghrepolist=$archivedGitHubRepos" | Out-File -FilePath $GITHUB_OUTPUT -Append

  get-content:
    runs-on: ubuntu-latest
    needs: get-gh-repos
    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Print the result
        shell: pwsh
        run: |
          Write-Output "List of repos:" 
          ${{ needs.get-gh-repos.outputs.ghrepolist }}
