name: Get archived SonarQube projects

on: 
  workflow_dispatch:
    inputs:
      ghOrganization:
        required: true
        type: string
      sonarQubeDomainName:
        required: true
        type: string
      sonarQubeToken:
        required: true
        type: string

jobs:
  get-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Masking values
        run: |
          echo "::add-mask::$ghOrganization"
          echo "::add-mask::$sonarQubeDomainName"
          echo "::add-mask::$sonarQubeToken"

      - name: Checkout action
        uses: actions/checkout@v3

      - name: Run PowerShell script
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_GH_PAT }}
          GITHUB_ORGANIZATION: ${{ inputs.ghOrganization }}
          SONARQUBE_DOMAIN_NAME: ${{ inputs.sonarQubeDomainName }}
          SONARQUBE_TOKEN: ${{ inputs.sonarQubeToken }}
        shell: pwsh
        run: |
          .\Scripts\Sonar-ArchivedGHRepos.ps1 `
            -ghOrganization $env:GITHUB_ORGANIZATION `
            -ghToken $env:GITHUB_TOKEN `
            -sonarQubeDomainName $env:SONARQUBE_DOMAIN_NAME`
            -sonarQubeToken $env:SONARQUBE_TOKEN
