name: Get archived SonarQube projects

on: workflow_dispatch

jobs:
  get-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Dot Soursing
        run: . .\Scripts\Sonar-ArchivedGHRepos.ps1
        shell: pwsh

      - name: Get archived GitHub repositories
        id: archivedghrepos
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_GH_PAT }}
          GITHUB_ORGANIZATION: "RoyalAholdDelhaize"
          SONARQUBE_DOMAIN_NAME: "sonar.ah.nl"
          SONARQUBE_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          . .\Scripts\Sonar-ArchivedGHRepos.ps1
          $archivedGitHubRepos = Get-ArchivedGHRepo -ghOrganization $env:GITHUB_ORGANIZATION -ghToken $env:GITHUB_TOKEN
          $archivedGitHubRepos | Out-File -FilePath .\archivedRepos.txt

      - name: Print the result
        shell: pwsh
        run: |
        Write-Output "List of repos:" 
        Get-Content .\archivedRepos.txt

