name: OPA Workflow

on: pull_request

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  policy-check:
    name: Policy check
    runs-on: ubuntu-latest
    container: openpolicyagent/conftest:v0.32.1
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Validate docker licenses
        id: validate
        run: |
          conftest test OPA/groups.yaml -n group -o github
          conftest test OPA/groups.yaml -n group -o json > summary.json
          if grep -q warning summary.json; then
            echo "warning=true" >> $GITHUB_OUTPUT
          else
            echo "warning=false" >> $GITHUB_OUTPUT
          fi
      - name: Write output for pull request
        uses: actions/github-script@v6
        if: steps.validate.outputs.warning == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |-
            const data = require('./summary.json');
            msg = data[0].warnings[0].msg;
            const output = `> **Warning**
            > ${msg}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: output
            })

# warning

