name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World"
      - name: Multiline script
        run: |
          node -v
          npm -v
      - name: Powershell core command
        run: |
          Get-Date
        shell: pwsh
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Output current directory in PS
        run: Get-Location
      - name: Output current directory in Bash
        run: pwd
        shell: bash